### ISSUE TITLE
[Enhancement] Third Person Visuals?

### ISSUE THREAD

**Issue by XanderCreates** [enjarai/do-a-barrel-roll#1]
Elytra Flight in Third person doesn't look all too exciting even with this mod installed, I would like to see third person visuals sometime in the future. Great Mod!

**Comment by enjarai** [comment]
This is definitely something I'll be working on adding on the client-side. Making it work for other players on the server though would be very difficult and beyond the scope of the mod.

**Comment by XanderCreates** [comment]
That's fine 👍

**Comment by enjarai** [comment]
Finally added in 1.3.0!

**Comment by XanderCreates** [comment]
huzzah!
