### ISSUE TITLE
Unknown custom packed identifier

### ISSUE THREAD

**Issue by QuantumFisch** [enjarai/do-a-barrel-roll#101]
I'm trying to join a server, but whenever i do i get a error
[Render thread/WARN]: Unknown custom packed identifier: do_a_barrel_roll:handshake
I don't know much about this , so there is little I can provide
I do have some mods installed but i never had any compatibility issues

**Comment by enjarai** [comment]
A server with Do a Barrel Roll installed will send that packet to clients to request a handshake, and if your client does not have the mod installed, that message will appear in your log. It's completely harmless though, and shouldn't prevent you from connecting, as indicated by the `WARN` status of the message, it is only a warning.

If you can't connect to your server, there might be something else going wrong. I can take a look if you send a paste link with your full log.

**Comment by QuantumFisch** [comment]
Thank You, but i solved it, it was just some cache files that caused the issues
