### ISSUE TITLE
Compatibility with Forge

### ISSUE THREAD

**Issue by SadEPa0628** [enjarai/do-a-barrel-roll#102]
This mod is no longer available in Forge after 1.19.4, which makes it impossible for me to use this mod with 1.20.1
![image](https://github.com/enjarai/do-a-barrel-roll/assets/120295331/cc45ecd8-e402-4a17-9cc3-8d4e366a4b19)

**Comment by Benonardo** [comment]
There won't be any official forge compatibility anymore, but you should be able to use https://github.com/Sinytra/Connector with this mod.

**Comment by SadEPa0628** [comment]
I am using a translation software, so please forgive me if there are any mistakes

**Comment by SadEPa0628** [comment]
Thank you, I will try to use this mod to make it compatible with Forge!
