### ISSUE TITLE
Process continues to run after a /stop or if the eula is false on the server side.

### ISSUE THREAD

**Issue by light672** [enjarai/do-a-barrel-roll#104]
It seems as if some thread is opened and never closed when the mod is loaded because if you try running the mod in a server through the terminal you can see that the process still remains open, which should not be the case.

Potential fixes:
    If the issue is caused by a hanging thread when a server starts (it appears it starts on the mod load so I am not sure) , consider saving the thread as a static variable and interrupting / stopping the thread upon the server closing.

**Comment by enjarai** [comment]
Should be fixed in 3.3.1.
