### ISSUE TITLE
Landing in Water doesn't cancel flight

### ISSUE THREAD

**Issue by Felina-Lain** [enjarai/do-a-barrel-roll#106]
**Describe the issue**
Landing in water (which I'm doing a lot of to train with the mod controls) does not cancel the flight mode.
Which means I'm stuck in the water until my feet touch the bottom, instead of being able to swim as in vanilla, after a second or two.
Deactivating the mod in water allows me to swim instantly.

It's not a big issue in small ponds and rivers, but it becomes a much bigger one when flying above the ocean.

**Crash report/logs (if applicable)**
NA

**Additional information**
NA

**Comment by carson-coder** [comment]
I think this happens in vanilla minecraft. Does this happen without the mod enabled

**Comment by carson-coder** [comment]
That is vanilla behavior. Unless DABR does stuff while the mod is disabled in settings.

**Comment by enjarai** [comment]
No, this is actually quite an issue when you have any of the DABR controls bound to WASD, because they will override the vanilla movement controls while in flight. I'll see if I can add an exception for when the player is submerged.

**Comment by carson-coder** [comment]
I tried vanilla minecraft (fabric with no mods) and I kept flying under water

**Comment by enjarai** [comment]
The flying itself isn't the issue, it's that DABR is overriding the WASD controls, making it impossible to move in the water while flying, which *is* possible in vanilla.

**Comment by Felina-Lain** [comment]
> I tried vanilla minecraft (fabric with no mods) and I kept flying under water

You CAN fly underwater in vanilla, but if you stay stationary in water (so you don't rocket to go forward) you'll eventually stop flying and start swimming. The delay can vary a bit, but it's between 1-3 seconds if you don't have any lag

But with the mod, since (as Enjarai said) it has its own input system that override the game one, it doesn't know that it should change behaviour when you hit water, so it keeps you in flight forever. And while you CAN rocket underwater to keep advancing, you're still unable to swim, and so landing in water isn't really landing, and makes it non-intuitive.



> No, this is actually quite an issue when you have any of the DABR controls bound to WASD, because they will override the vanilla movement controls while in flight. I'll see if I can add an exception for when the player is submerged.

I'll wait for an update then :)
(btw: the mod is incredible, the cinematic feeling of flying above my base was *chef kiss*)

**Comment by carson-coder** [comment]
Ok

**Comment by enjarai** [comment]
Forgot to close this, but it's fixed in 3.3.2.
