### ISSUE TITLE
Can authors consider customizable buttons?

### ISSUE THREAD

**Issue by BestRyze** [enjarai/do-a-barrel-roll#109]
In many flying games such ACE combat, battlefied, players offen use A/D to control axis roll, W/S and mouse Y to control axis pitch and use mouse X to control axis yaw.  Sincerely hope the author can add this function.

**Comment by enjarai** [comment]
This is already a thing in the latest versions. Make sure you're up to date, and check your controls menu.

**Comment by BestRyze** [comment]
Thx!
