### ISSUE TITLE
Backport to 1.16 for the sole reason of being able to use it with TSF

### ISSUE THREAD

**Issue by enjarai** [enjarai/do-a-barrel-roll#11]
Need I say more?

**Comment by XanderCreates** [comment]
of course they didnt update TSF for java.. smh.

**Comment by Endninja137** [comment]
> of course they didnt update TSF for java.. smh.

I'm pretty sure they did. The original was released for 1.11, then they re-released it for 1.16.5

**Comment by XanderCreates** [comment]
> > of course they didnt update TSF for java.. smh.
> 
> I'm pretty sure they did. The original was released for 1.11, then they re-released it for 1.16.5

I meant, once again. After 1.16 they just stopped...

**Comment by enjarai** [comment]
For anyone interested in playing TSF with this mod, I've recently booted up a server to host a modified version of TSF on 1.19.4. The server requires you to have DABR installed, and PB times are recorded in my discord. You can join via the discord as well.

Alternatively, @Benonardo made a janky 1.16 backport in the https://github.com/enjarai/do-a-barrel-roll/tree/1.16.5-jankport branch. If you want to play in singleplayer, this might be a solution.

Due to these options being available now, I'm finally closing this issue.
