### ISSUE TITLE
[Enhancement] Hang Glider Compat

### ISSUE THREAD

**Issue by SafeOfArsenal** [enjarai/do-a-barrel-roll#111]
**Describe the issue**
consistency basically

**Crash report/logs (if applicable)**
Upload your crash report or logs here if they could be of help when trying to diagnose the issue. Please use https://mclo.gs/ instead of uploading the file directly.

**Additional information**
https://www.curseforge.com/minecraft/mc-mods/hang-glider

**Comment by enjarai** [comment]
This would require quite a different physics model to make sense, which is a lot of work for something that probably wont be used much. This suggestion is currently considered out of scope.
