### ISSUE TITLE
`... did not accept config syncing, config indicates we kick them.` spam in logs

### ISSUE THREAD

**Issue by axd1x8a** [enjarai/do-a-barrel-roll#112]
**Describe the issue**
When player not connected to server, mod just spam that in logs, sometimes even targeting `Conductor` from `Create: Steam and Rails`
Fabric 1.19.2, mod version: 2.6.2
**Additional information**
![image](https://github.com/enjarai/do-a-barrel-roll/assets/26704473/43037bc3-ae45-41fe-a6e2-728b1545bb47)

**Comment by enjarai** [comment]
Thats quite strange, might be an incompatibility with steam and rails? I've already stopped maintaining pre-1.19.4 versions of this mod though, so I probably wont be implementing a fix for this. 

Even so, you should still be able to prevent the error from showing up by disabling the option to require players that join to have the mod. If that's not an option, you can try compiling your own version without the line that logs this specific error, assuming this problem doesn't affect anything outside of the logs.

See:
https://github.com/enjarai/do-a-barrel-roll/blob/1.19.2/legacy/common/src/main/java/nl/enjarai/doabarrelroll/api/net/HandshakeServer.java#L57

**Comment by axd1x8a** [comment]
It looks like the player is not being removed from the queue and the mod keeps trying to kick him, I don't know if this happens in 1.20 but I'll try to figure it out and send a PR with fixes for 1.19
