### ISSUE TITLE
Please update 1.20.4

### ISSUE THREAD

**Issue by KdGaming0** [enjarai/do-a-barrel-roll#116]
I would love it if you could update it to 1.20.4. I love the mod and want to use it. 

if you can't I totally understand I just want to use it so much.

**Comment by Dev0Louis** [comment]
Done in https://github.com/enjarai/do-a-barrel-roll/pull/117

**Comment by Kyorith** [comment]
> Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.3.7+1.20.2 with any version that is compatible with:
		 - minecraft 1.20.4
More details:
	 - Mod 'Do a Barrel Roll' (do_a_barrel_roll) 3.3.7+1.20.2 requires any version between 1.20.2- (inclusive) and 1.20.3- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.4!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

Doesn't seem to work in 1.20.4 for me

Edit: Newest Release fixed the issue

**Comment by enjarai** [comment]
Forgor to close this, 1.20.4 update was released a while ago.
