### ISSUE TITLE
[Feature]: Camera seperation

### ISSUE THREAD

**Issue by BioTechproject27** [enjarai/do-a-barrel-roll#119]
So, landing without taking some amount of fall dmg is pretty difficult and switching with f5 to front cam view is also a bit inconvenient. Also being able to look around while flying would be cool, without changing direction, especially in tighter places.

All the mods that allow for that seem to only do so by permanently detaching the camera until a button is pressed again, or don't snap the camera back to the original location (e.g. with [tweakeroo)](https://github.com/maruohon/tweakeroo), which usually does so), so you have to turn back where you were looking before.

So having a keybind (e.g. button 5 on the mouse) that allows for looking around would be nice, so I can finally see where I'm landing and don't overshoot

**Comment by enjarai** [comment]
I consider this to be out of scope for this mod. You may be better off looking for a mod that does this specifically.

**Comment by BioTechproject27** [comment]
The problem is that they're not compatible:
> don't snap the camera back to the original location (e.g. with [tweakeroo)](https://github.com/maruohon/tweakeroo), which usually does so), so you have to turn back where you were looking before.

You can't turn the camera seperately, they all start turning/don't snap back.

**Comment by BioTechproject27** [comment]
Sad to see such a great project neglected :(
