### ISSUE TITLE
Flying doesn't work underwater

### ISSUE THREAD

**Issue by TooMuchHuke** [enjarai/do-a-barrel-roll#121]
When you are using the elytra underwater, it doesn't have the effect this mod provides. To recreate, start flying, then slowly descend into deep water. Your camera will snap to facing directly forward, and you can't see any roll effect anymore.

**Comment by enjarai** [comment]
This is the default behaviour yes, as it can be difficult to get out of elytra mode in water, easily causing unintentional drowning. You can disable this in the config though, letting you roll underwater.
