### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by OutsiderH** [enjarai/do-a-barrel-roll#122]
The game crashed when I try to use your mod as dependency of mine mod.

mod version is 2.6.2+1.19.2-fabric

```
org.spongepowered.asm.mixin.transformer.throwables.MixinPreProcessorException: Attach error for fungible.mixins.json:NarratorMixin from mod fungible during activity: [Transform -> Method getNarrator()Lcom/mojang/text2speech/Narrator; -> INVOKESPECIAL -> com/mojang/text2speech/NarratorDummy::<init>:()V]
```

**Comment by enjarai** [comment]
This looks like an issue with fungible, not my mod. Make sure you use the right version of that mod.

**Comment by OutsiderH** [comment]
The version is specified by your mod's maven repository, is there any way to change that?
