### ISSUE TITLE
Crashed for unknown reason

### ISSUE THREAD

**Issue by AquaticShelter** [enjarai/do-a-barrel-roll#125]
**Describe the issue**
yes it crashed when i launch minecraft.

**Crash report/logs (if applicable)**
[crash-2024-03-06_11.51.30-client.txt](https://github.com/enjarai/do-a-barrel-roll/files/14504784/crash-2024-03-06_11.51.30-client.txt)

**Additional information**
please show me some ways

**Comment by kikugie** [comment]
It is caused by optifine, which DABR is incompatible with

**Comment by enjarai** [comment]
Yes, optifine is not supported.
