### ISSUE TITLE
[Feature Suggestion] Launch Start

### ISSUE THREAD

**Issue by MCYCShadow** [enjarai/do-a-barrel-roll#126]
Hey,

loving the Mod. Hope it's fine to post a suggestion for a feature update.
The "Launch Start", an alternative start method, which would be, Sneaking, Looking up, and then Jump to start with a boost upwards.

Edit: Maybe a general option for the Pitch to have a deadzone for lift off would also be an addition the existing mode could benefit from.

Cheers.

**Comment by enjarai** [comment]
I'd consider this to be out of scope for what this mod tries to achieve, especially considering there are other mods that do similar things. Thanks for the suggestion though!
