### ISSUE TITLE
HUD elements missing in Forge builds version 3.5.2+1.20.1 and above

### ISSUE THREAD

**Issue by amelia-bartlett** [enjarai/do-a-barrel-roll#127]
**Describe the issue**
HUD elements (horizon indicator, momentum-based mouse) do not show up on Forge builds starting from version 3.5.2+1.20.1 even when enabled (they function fine on quilt builds).  Everything else appears to work properly.

Tested against the following versions:
1:
Do a Barrel Roll 3.5.3+1.20.1 from Modrinth
Minecraft 1.20.1
Quilt Loader 0.24.0
CICADA 0.6.2+1.20.1-and-below from Modrinth
Mod Menu 7.2.2 from Modrinth
Quilted Fabric API 7.5.0+0.91.0-1.20.1 from Modrinth
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
log file: https://mclo.gs/0D34J3i
Result: Expected behaviour

2:
Do a Barrel Roll 3.5.3+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.2.0
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
log file: https://mclo.gs/fXgzwih
Result: HUD elements missing

3:
Do a Barrel Roll 3.5.3+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.1.3
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
Result: HUD elements missing

4:
Do a Barrel Roll 3.5.2+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.1.3
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
A bunch of other mods (this one was my personal modpack where I initially noticed the issue - I also tested Do a Barrel Roll 3.5.3+1.20.1 from Modrinth and had the same issue here)
Result: HUD elements missing

5:
Do a Barrel Roll 3.4.0+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.2.0
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
Forgified Fabric API 0.92.0+1.11.3+1.20.1 from Modrinth
Result: Expected behaviour

6:
Do a Barrel Roll 3.5.0+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.2.0
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
log file: https://mclo.gs/ikVARe1
Result: Expected behaviour

7:
Do a Barrel Roll 3.5.1+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.2.0
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
log file: https://mclo.gs/Fj6qcDE
Result: Expected behaviour

8:
Do a Barrel Roll 3.5.2+1.20.1 from Modrinth
Minecraft 1.20.1
Forge 47.2.0
YetAnotherConfigLib 3.2.2+1.20 from Modrinth
log file: https://mclo.gs/0mp31W3
Result: HUD elements missing

**Crash report/logs (if applicable)**
I didn't notice anything interesting in the logs that appeared to be relevant to your mod
Upload your crash report or logs here if they could be of help when trying to diagnose the issue. Please use https://mclo.gs/ instead of uploading the file directly.
Log files above, by the versions that I had them for (I lost some of them, sorry!)

**Additional information**
Put any additional info here. e.g. screenshots/videos, config files.
I could not install Mod Menu or CICADA on Forge as they are not available
I am running Fedora Linux with proprietary NVIDIA GPU drivers (yes, the notoriously buggy ones) - I am getting new hardware with a non-NVIDIA GPU very soon so I should be able to retest if needed.
The crash in the logs occurs regardless of what mods I have installed, and appears to be a problem with the aforementioned gpu drivers.
Forgified Fabric API was removed as a dependency starting at Do a Barrel Roll 3.5.0+1.20.1
My initial hypothesis was that something in the mod was depending on something from fabric/quilt and this wasnt ported forwards, but upon testing 3.5.0+1.20.1 this hypothesis was disproven.
The changelog for the version of the mod where this bug was introduced is as follows:
 + Reworked some old mixins using newly gained skill.
   + This should generally improve compatibility.
   + In fact, this already fixes a crash with the Real Camera mod.

**Comment by enjarai** [comment]
Thanks for the detailed report, It's not unlikely that I messed up with some mixin changes somewhere in that update. I'll do some digging.

**Comment by enjarai** [comment]
I'm not quite sure why its failing quietly, but I have found the cause of the issue. It seems like forge modifies the hud rendering compared to vanilla, which, after I made my mixin for it more specific, caused it to miss the mark. This should be easy to fix by making a specific version of the mixin designed for forge.

**Comment by enjarai** [comment]
Just pushed a hotfix to patch this issue, please try it out and let me know if it works!

**Comment by amelia-bartlett** [comment]
> Just pushed a hotfix to patch this issue, please try it out and let me know if it works!

I will be trying it out later today, thanks!

**Comment by amelia-bartlett** [comment]
I can confirm that the bug has been fixed by  Do a Barrel Roll 3.5.4+1.20.1 from Modrinth
