### ISSUE TITLE
Game crashes when using elytra

### ISSUE THREAD

**Issue by Rickrollv2** [enjarai/do-a-barrel-roll#128]
This hasn't happened until just recently, probably after updating. As soon as I launch my elytra, the game crashes. Not Enough Crashes tells me it's due to this mod, which makes sense. I have a lot of other mods so they might be the problem.

https://mclo.gs/Eqk38KD

**Comment by enjarai** [comment]
The crash report seems to be blaming Physics Mod, though that could be related to Not Enough Crashes obfuscating things. (It is a bad mod, I recommend not using it.) I do notice that you're using Controlify 2.0 though, which is currently not supported by DABR and crashes in exactly this way. Consider downgrading it to a 1.x version.
