### ISSUE TITLE
Migrate to a different config library, seeing as Cloth Config is effectively depricated.

### ISSUE THREAD

**Issue by enjarai** [enjarai/do-a-barrel-roll#13]
![image](https://user-images.githubusercontent.com/38552516/187265449-9aeccf04-0e8c-41b3-9bfc-bb3260353435.png)
![image](https://user-images.githubusercontent.com/38552516/187265465-9e00fabd-afbc-468b-8eb9-75b1509f1567.png)

**Comment by enjarai** [comment]
The alternative would likely be owo-lib's config module. I'm open to alternative suggestions.

**Comment by Motschen** [comment]
I'm a bit biased on that, but [MidnightLib](https://github.com/TeamMidnightDust/MidnightLib) is focused on being very small for JiJ usage, while still providing a full config experience, all in literally only 60KB.
Also, it's just so easy to create config entries, it's literally done in one line, which helps me in a lot of debugging scenarios where I need to try some different values, but don't want to recompile to mod to change it.
Despite of it's small file size, it still provides some other nice features, like color utilities, automatic ModMenu integration and cosmetic hats for modders, which I think is a great way us modders can get rewarded for all the hard work we do. 
If you don't like the extra features however, you can also literally use the MidnightConfig class on it's own, as it basically contains the entire config system.

**Comment by enjarai** [comment]
I prefer something annotation-based, its very convenient to be able to add a few lines and have everything just work™.

**Comment by Motschen** [comment]
> I prefer something annotation-based, its very convenient to be able to add a few lines and have everything just work™.

Yeah, that's exactly what MidnightConfig is, an annotation-based config library that just works.

**Comment by enjarai** [comment]
Oh really? For some reason I was under the impression that it's builder-based. I'm not a huge fan of the bundled cosmetics idea, but as its possible to use only the config parts, I'll take a look. 

Are nested objects supported? How does it handle default values for those? I've had issues with cloth not liking it when I specify default values for nested objects as constructor arguments instead of putting them in the class directly.

**Comment by Motschen** [comment]
> Are nested objects supported? How does it handle default values for those? I've had issues with cloth not liking it when I specify default values for nested objects as constructor arguments instead of putting them in the class directly.

No, they are not, as that would dramatically increase the file size and it's used so rarely that I don't think it's a necessity for a config library focused on size.

**Comment by Endninja137** [comment]
If possible, it would be great if you just had the MidnightConfig class built into the mod,
as then it would no longer require any separate dependencies.
