### ISSUE TITLE
[SUGGESTION] Add joystick support

### ISSUE THREAD

**Issue by Batimius** [enjarai/do-a-barrel-roll#133]
Hello there. Judging from the title, you probably already know what this issue is about. My suggestion is, adding support for controlling your elytra with a joystick. Now, I am not sure if this is possible, whether the limitations come from the mod, the libraries, or even the engine (such as unsupported joystick support), but if possible, I believe that the support of an actual joystick would be epic.

I own a Logitech Extreme 3D Pro, and it seems like the fitting tool for controlling your elytra. Since the mod is made to have the gliding mechanics of the plane, why not add the ability to control it **like** a plane by using a joystick? I feel like such mechanic would help with immersion a lot.

**Comment by Benonardo** [comment]
If you're playing on Fabric, you can use the [Controlify](https://modrinth.com/mod/controlify) mod to achieve this. It should generally work well with most joysticks and is compatible with DABR.

**Comment by enjarai** [comment]
Yup, this has been implemented via Controlify. DABR provides a bunch of elytra-specific bindings in the Controlify settings menu, with which you should be able to configure any joystick to work with the mod. Let me know if you encounter any issues!
