### ISSUE TITLE
is still possible to activate the mod while on water

### ISSUE THREAD

**Issue by peow** [enjarai/do-a-barrel-roll#134]
even though you have the option to disable the mod while underwater, you can still activate the mod while swimming, you just need to hold down the **space bar** to stay on the surface

![2024-04-12_11 19 35](https://github.com/enjarai/do-a-barrel-roll/assets/105888751/2596ae65-90b5-45a8-a3f1-7f3c7cd9997a)
![2024-04-12_11 19 39](https://github.com/enjarai/do-a-barrel-roll/assets/105888751/4404a9a2-ef2d-4d1a-9d2d-0fd0a7b35164)
![2024-04-12_11 19 47](https://github.com/enjarai/do-a-barrel-roll/assets/105888751/0124ec81-4145-48ee-bfb5-233cc1bea3e3)

*using latest Fabric 1.20.1 version

**Comment by enjarai** [comment]
This is because you technically leave the water when you do this. I consider it a non-issue, as it doesn't prevent you from swimming to safety.
