### ISSUE TITLE
Crash when control is connected with Controlify 2 installed

### ISSUE THREAD

**Issue by Josh65-2201** [enjarai/do-a-barrel-roll#136]
**Describe the issue**
I'm uncertain whose side this is on so I have posted on both https://github.com/isXander/Controlify/issues/287

**Crash report/logs (if applicable)**
https://mclo.gs/JMd0zv0

**Additional information**
Put any additional info here. e.g. screenshots/videos, config files.

**Comment by ezra-351** [comment]
having a similar issue where controlify doesn't detect any controllers while DABR is enabled.

**Comment by enjarai** [comment]
Should be fixed with recent updates.
