### ISSUE TITLE
suggestion/request - Swimming

### ISSUE THREAD

**Issue by DemonSlayer112** [enjarai/do-a-barrel-roll#137]
**Idea**
Could we have the ability to enable the mod for swimming? Would make swimming in large oceans much more interactive!
Or if someone could hint at a existing mod, but i would love this mod to be able to do this, im sure it could already, but him hopefull for a real swimming method without elytra durability going down.
Also if this does get considered ty! :D
But also would probably need a separate config option, I assume some people wont want this and only the elytra rolls.

**Comment by enjarai** [comment]
This has actually been suggested before, and is being worked on as an addon mod. Check out the #rolling-down-in-the-deep channel in my discord to keep up to date on development.

**Comment by enjarai** [comment]
I've released Rolling Down in the Deep as a beta. It still has quite a few issues, but I thought I'd get it out there at least. Please do try it out and leave any suggestions on its github!

https://modrinth.com/mod/rolling-down-in-the-deep
