### ISSUE TITLE
Mod not working

### ISSUE THREAD

**Issue by CozzDlp** [enjarai/do-a-barrel-roll#138]
I installed this mod for fabric and although I also installed fabric API and Cicada LIB (first only api, then both together) the mod doesn't work.
the game starts without problems but when I try to fly with the Elytra absolutely nothing has changed (neither moving with the mouse, nor with WASD nor with the arrows)
I play as Lunar Client so I don't want that to be the problem
all installations (including the game version) are on 1.20.1
I don't have any other mods installed besides this one
I tried both singleplayer and multiplayer

**Comment by enjarai** [comment]
You'll want to double check if you have the mod enabled in the ingame config. There's a keybind for it that you might have pressed accidentally. If that isn't the issue, there is a rare bug where the mod will sometimes just not work™, but thats known to fix itself after a game restart.

**Comment by CozzDlp** [comment]
can u tell me which keyblind is? or where to check it?
cause in the custom keyblind I don't see nothing new but the lunar pre-installed mods

**Comment by enjarai** [comment]
You should be able to find it in the vanilla keybinds menu. If not, lunar might be interfering somehow?
