### ISSUE TITLE
Suggestion: sensitivity increase along with flight speed (pitch and yaw)

### ISSUE THREAD

**Issue by dlfnn** [enjarai/do-a-barrel-roll#14]
Why? When, for example, I jump off a cliff and want to pitch down to 90 degree and often over-pitch it so ending up hitting the cliff, while I am flying at high speed towards a pillar (with the same sensitivity) I attempt to avoid it but often didn't turn my pitch or yaw enoughly, ending up on the wall again...

**Comment by enjarai** [comment]
I feel like inconsistent sensitivity would cause more issues that it solves, especially when it increases at high speeds. I can easily imagine myself pitching more than expected and hitting something.

**Comment by dlfnn** [comment]
But I think it kinda makes sense that you have to stablize your mouse control more during high speed. Think of it as driving a car, that when you wanna turn 90° just after you start up you may have to turn the wheel for like two or more loops, but on high speed your car would drift even when you turn half loop... just so players need to turn more subtle during high speed? Or maybe

**Comment by enjarai** [comment]
I see, there are currently a bunch of flight mechanics suggestions piled up which I don't quite have the time to deal with, but I'll keep this on the list to try out later.

**Comment by dlfnn** [comment]
Sorry, I don't really know how to do so ; ;

**Comment by enjarai** [comment]
No problem, I don't really have time to do it myself at the moment though. But I'll get around to it eventually.

**Comment by enjarai** [comment]
Major enhancements to flight dynamics have already been made recently, and I don't feel like this feature will improve them further. 

Marking as wontfix.
