### ISSUE TITLE
mod being flagged as malware

### ISSUE THREAD

**Issue by papamaionise** [enjarai/do-a-barrel-roll#140]
![Screenshot (1411)](https://github.com/enjarai/do-a-barrel-roll/assets/126779287/619ff537-cac9-4c15-b48f-4181b85c013a)

**Comment by papamaionise** [comment]
false positive probably?

**Comment by enjarai** [comment]
I sure do hope thats a false positive yea, I know that windows defender had a bunch with mc mods lately. You could try running it through virustotal, which should be more reliable.
