### ISSUE TITLE
[QUESTION] Java noob here, how do you compile this mod ?

### ISSUE THREAD

**Issue by remidu64** [enjarai/do-a-barrel-roll#144]
I know you have to execute the gradlew.bat file but i get fatal errors when i try to compile it (see image)
![image](https://github.com/enjarai/do-a-barrel-roll/assets/60043514/86ad7597-9c9c-477c-857f-e2818336f47f)

How do i fix this ?

(sorry btw if the answer obvious, i'm a complete Java noob)

**Comment by Dev0Louis** [comment]
cardinal components seems not to be found. Did you change anything in the mod?

**Comment by remidu64** [comment]
i didnt change anything

(and damn i didnt expect an answer that quickly lol)

**Comment by remidu64** [comment]
forgor to say that i'm trying to compile the 1.19.2 version

**Comment by Dev0Louis** [comment]
Oh yeah the maven repo moved. If you want to try you could try to add 

```
    maven {
        name = 'Ladysnake Mods'
        url = 'https://maven.ladysnake.org/releases'
    }
```

into to the repositories block. 
    
The old versioned isn't really supported anymore btw.
    
 If you don't know how to make the needed changes you could also get the version from modrinth: https://modrinth.com/mod/do-a-barrel-roll/version/2.6.2+1.19-fabric. Just be aware that you won't get support for it as 1.19.2 is not supported anymore and an old version.

**Comment by remidu64** [comment]
alright

**Comment by remidu64** [comment]
where do i add the "maven" code to ? (aka which file)

**Comment by Dev0Louis** [comment]
you should add it to the build.gradle

**Comment by remidu64** [comment]
okay thanks
