### ISSUE TITLE
Player movement camera animation breaks after flying with elytra (Shaders compatibility)

### ISSUE THREAD

**Issue by Jonyee04** [enjarai/do-a-barrel-roll#146]
When the player moves for the first time there is no problem, unless you fly and come back to the ground with the shader enabled, then the animation doesn't work

There is no crash file since the game didn't crash

but i am using these mods:
![image](https://github.com/enjarai/do-a-barrel-roll/assets/103516099/b14f6a9e-bccb-493d-9b08-2a5ef9c1a1d6)

**Comment by enjarai** [comment]
The ongoing Iris incompatibility issue is being tracked in #143. The problem you mention is a result of the temporary fix we've applied to prevent a full crash.
