### ISSUE TITLE
Camera lose it's shaking when using iris shaders in 3.5.8 with 1.20.6 after a flight

### ISSUE THREAD

**Issue by PingGai** [enjarai/do-a-barrel-roll#147]
**Describe the issue**
Symptoms: 
When the shader is enabled, the camera does not shake (just like when camera shaking is turned off).
Reproduction: 
This issue is triggered when the mod is installed alongside the Iris mod and a shader (such as BSL) is enabled during flight. The issue does not occur without enabling a shader.

**Additional information**
Mod List:
![image](https://github.com/enjarai/do-a-barrel-roll/assets/70486553/eca4a164-7650-4a56-9a8a-3db4ddaba85a)
Vedio:
https://github.com/enjarai/do-a-barrel-roll/assets/70486553/f0c12fe0-fc0d-4e53-8d09-905c8325ecab

**Comment by enjarai** [comment]
I'm aware of this issue, we are currently working on a fix. #143 is being used to track the current status.
