### ISSUE TITLE
Weird camera shake on flight in 1.20.1 (latest version)

### ISSUE THREAD

**Issue by MatchTerm** [enjarai/do-a-barrel-roll#148]
**Describe the issue**
So, to preface this, tested both in the pure forge port that was made for 1.20.1 and also the fabric version by using the syntra connector. I am aware there is a similar issue in 1.20.6, but regarding on the ground after, so I feel like this is different.

Essentially, it appears that, when in flight the camera is... weirdly shaking. It's fine when on the ground, no problem there, but I do a maneuver like a loop, and it starts shaking very weirdly

**Crash report/logs (if applicable)**
No actual crashing

**Additional information**
Here's a list of my mods currently (running DABR through the connector):
[modlist.txt](https://github.com/enjarai/do-a-barrel-roll/files/15431978/modlist.txt)
And a video of the issue:

https://github.com/enjarai/do-a-barrel-roll/assets/28060353/ceb5a92c-aa91-4e97-bd0d-157fefc93d95

**Comment by enjarai** [comment]
The problem is most likely some other mod interfering with an important mixin. I do know that Forge mods have a higher than normal tendency to improperly write mixins, causing unnessecary incompatibilities.

It's impossible to tell what mod is causing the issue from just a modlist and a video, so you may have to do a binary search on your mods folder to isolate the source.

**Comment by MatchTerm** [comment]
> The problem is most likely some other mod interfering with an important mixin. I do know that Forge mods have a higher than normal tendency to improperly write mixins, causing unnessecary incompatibilities.
> 
> It's impossible to tell what mod is causing the issue from just a modlist and a video, so you may have to do a binary search on your mods folder to isolate the source.

I see. Well, thank you still, just wanted to rule out the mod itself having issues.

**Comment by enjarai** [comment]
Do let me know if you find the problematic mod, as that might let me make a compatibility patch on my side.

**Comment by MatchTerm** [comment]
> Do let me know if you find the problematic mod, as that might let me make a compatibility patch on my side.

Found it! Turning this mod off fixed it: https://modrinth.com/mod/create-train-perspective

**Comment by MatchTerm** [comment]
I guess it makes sense it wouldn't play nice with this.

**Comment by MatchTerm** [comment]
I'll reopen to make sure you can see it since you were interested :)

**Comment by enjarai** [comment]
Ah I see, the dev of that mod seems to be aware of the issue (https://github.com/der-fruhling-entertainment/create-train-perspective/issues/56), so I expect it'll be fixed at some point in the future.
