### ISSUE TITLE
This mod with Controlify beta 9 doesn't load

### ISSUE THREAD

**Issue by Josh65-2201** [enjarai/do-a-barrel-roll#149]
## Logs
[latest.log](https://github.com/enjarai/do-a-barrel-roll/files/15443720/latest.log)

## Versions
Minecraft: 1.20.1
Mod loader: Quilt 0.26.0 beta 2
Do a barrel roll: 3.5.6
Controlify: 2.0.0 beta 9

**Comment by enjarai** [comment]
I'm aware beta 9 is currently not compatible, this is work in progress.

**Comment by enjarai** [comment]
Fixed as of 3.5.10.
