### ISSUE TITLE
controlify support appears broken, at least on 1.20.1?

### ISSUE THREAD

**Issue by alexbobp** [enjarai/do-a-barrel-roll#155]
**Describe the issue**
I got a crash when using this mod together with controlify on 1.20.1.  It appears to be (to my untrained eye) a result of do-a-barrel-roll trying to explicitly support controlify, but it failed.

I tested this by making a minimal modpack in prism launcher: I selected 1.20.1, quilt launcher, and just added do-a-barrel-roll and controlify, as well as the dependencies that got pulled in automatically.
The total modlist came out to:
- CICADA
- Controlify
- Do a Barrel Roll
- Quilted Fabric API
- YetAnotherConfigLib

**Crash report/logs (if applicable)**
https://mclo.gs/gVIkG5b

**Comment by alexbobp** [comment]
Okay, on advice from copygirl, I worked my way through controlify versions.  The incompatibility is introduced in Controlify 2.0.0-beta-11.  Beta-10 appears to work fine.  I hope that info helps.

**Comment by enjarai** [comment]
Fixed in 3.6.1.
