### ISSUE TITLE
Error loading resource packages when starting with Controlify

### ISSUE THREAD

**Issue by xleb-normal** [enjarai/do-a-barrel-roll#157]
**Describe the issue**
When loading Minecraft with Do a Barrel Roll and Controlify with a resource pack already enabled, or when trying to enable a resource pack, the game displays a resource pack loading error message

**Crash report/logs (if applicable)**
https://mclo.gs/TFvLMrn

**Additional information**
video https://youtu.be/vs2R1vaEWfo

Tested on an empty instances with mods
- fabric-api-0.92.2+1.20.1
- YetAnotherConfigLib-3.5.0+1.20.1-fabric
- Controlify-2.0.0-beta.13+1.20.1-fabric
- do_a_barrel_roll-fabric-3.6.0+1.20.1
- cicada-lib-0.8.1+1.20.1

**Comment by enjarai** [comment]
Controlify unexpectedly made a breaking change in their API in recent betas which I havent released a fix for yet. Until I release an update, it should work if you downgrade Controlify slightly.

This issue is primarily tracked in #155
