### ISSUE TITLE
[BUG] When landing with any GUI open, the camera orientation does not reset until the GUI is closed

### ISSUE THREAD

**Issue by pkstDev** [enjarai/do-a-barrel-roll#16]
![2022-09-17_22 27 52](https://user-images.githubusercontent.com/62203463/190862087-7b9c1763-b4f1-414d-a142-d003f95860c4.png)

**Comment by enjarai** [comment]
Are you using the latest version? I'm pretty sure I've caught this before with the pause screen and fixed it. This might be a seperate bug though.

**Comment by apicella1** [comment]
This does this for me as well if you open the chat menu.
