### ISSUE TITLE
Switch Roll and Yaw setting both A/D and mouse_x to Yaw

### ISSUE THREAD

**Issue by SpasticDovah** [enjarai/do-a-barrel-roll#162]
Hi, thank you for your amazing mod. I've run into a problem while messing with the configs, however.

I've toggled the "switch_roll_and_yaw" option to "true". Upon testing elytra flight in-game though, A/D still changes the yaw, albeit at a significantly faster rate than my mouse_x. To clarify, both A/D and horizontal mouse movement are altering my yaw, leaving me no way to roll. Everything works fine if I revert "switch_roll_and_yaw" to "false"--I am able to roll with mouse_x and yaw with A/D. This control scheme is unintuitive to me, unfortunately.

I tested your mod (v3.5.6+1.20.1) on Forge (v47.2.0), with no other mods enabled. I have banking, thrust, and disable_when_submerged as false, if that helps. Actually I'll just paste my configs here. Please let me know if this problem can't be reproduced on your end, or if you have any questions.

[do_a_barrel_roll-client.json](https://github.com/user-attachments/files/16517687/do_a_barrel_roll-client.json)

**Comment by enjarai** [comment]
After switching mouse axes, you probably want to reconfigure the keybinds as well. You can do that in the vanilla controls menu.
