### ISSUE TITLE
A quick question, can I disable the mouse drag.

### ISSUE THREAD

**Issue by AC5174765920** [enjarai/do-a-barrel-roll#163]
**Describe the issue**
How to disable the mouse drag please? I toggled on and off everything in the config menu but it seems not working. Mouse drag means when mouse stops, there are still excessive momentum of camera, can we have it to stop immediately after my mouse stops?

**Crash report/logs (if applicable)**
N/A

**Additional information**
N/A

**Comment by enjarai** [comment]
You can completely disable mouse drag, or smoothing as its called in the mod, using a toggle in the `Sensitivity` tab of the config.
