### ISSUE TITLE
This mod conflicts with the Create

### ISSUE THREAD

**Issue by system-jiangnan** [enjarai/do-a-barrel-roll#164]
This mod causes Create to be unable to enter the thinking interface (it directly crashes the game when opened), version: 1.20.1 fabric

**Comment by enjarai** [comment]
Please share your full log after the crash.

**Comment by system-jiangnan** [comment]
[latest.log](https://github.com/user-attachments/files/16811693/latest.log)
Sorry, my email bar took this message as spam.

**Comment by system-jiangnan** [comment]
Chinese has become garbled in the crash log.

**Comment by system-jiangnan** [comment]
[crash-2024-08-23_14.11.47-client.txt](https://github.com/user-attachments/files/16811724/crash-2024-08-23_14.11.47-client.txt)
and this

**Comment by enjarai** [comment]
Do a Barrel Roll is not loaded in the log files you've provided. The issue is most likely unrelated. Feel free to reopen if you have reason to believe otherwise.
