### ISSUE TITLE
How did you use this with Terra Swoop Force?

### ISSUE THREAD

**Issue by sebastian777-jp** [enjarai/do-a-barrel-roll#17]
Would love some help, please, @enjarai

**Comment by enjarai** [comment]
Currently the only way is to use ViaVersion/ViaFabric to connect to a 1.16 server with a 1.18/1.19 client. From my experience this creates no issues. I do have plans to backport to 1.16 eventually though.

**Comment by Tejty** [comment]
Can you give me a more specific way how to do that please? Thank you.
Very good mod tho
