### ISSUE TITLE
Do a barrel roll, does not launch game 

### ISSUE THREAD

**Issue by Kloytz** [enjarai/do-a-barrel-roll#171]
After updating to newest do a barrel roll version for 1.21.1, the game just won't start it does not even crash the game, straight up not starting 

https://mclo.gs/ilNC8yv

Without do a barrel roll
![image](https://github.com/user-attachments/assets/bf5d2d7a-086b-4c4c-adc6-1a4940989ab0)
With do a barrel roll
![image](https://github.com/user-attachments/assets/82fb2a7c-7282-4c62-b5ad-3c38678b396b)

**Comment by LordEnder-Kitty** [comment]
I'm getting a similar issue. 
(My logs are a lot less cluttered, so it might be easier to figure it out from mine)

https://mclo.gs/zH5rGkZ

**Comment by Wolfkid200444** [comment]
Same issue here

**Comment by lilCactus71** [comment]
guys just use the older version, the dev is asleep rn so just revert to older version

**Comment by enjarai** [comment]
Fixed in 3.7.1.
