### ISSUE TITLE
NeoForge Version is asking for fabric_api

### ISSUE THREAD

**Issue by Azari-k** [enjarai/do-a-barrel-roll#176]
Details:
	Mod file: /C:/Users/Home/AppData/Roaming/.minecraft/mods/do_a_barrel_roll-neoforge-3.7.2+1.21.jar
	Failure message: Mod do_a_barrel_roll requires fabric_api any
		Currently, fabric_api is not installed
		
I tried to add fabric_api to the mods folder but as expected, NeoForge wouldn't read it because it's for fabric

**Comment by basmgg** [comment]
Just install (Forgified Fabric API)

**Comment by Azari-k** [comment]
> Just install (Forgified Fabric API)

i tried looking for something like this but couldn't find it, thank you!!

**Comment by Azari-k** [comment]
.
