### ISSUE TITLE
Not exiting out of elytra movement when touching ground

### ISSUE THREAD

**Issue by LemonHeadOnGit** [enjarai/do-a-barrel-roll#178]
**Describe the issue**
When using this mod, along with many others (I will try to deduce any conflict in the meantime), the game doesn't seem to properly register when the player is no longer in flight mode. Even when taking off the elytra, the game still thinks I am flying with one. This means that the only way to exit said mode is either by turning going to Creative mode and initiating creative flight, or dying.

**Crash report/logs (if applicable)**
Nothing seemed to appear in the logs when this issue happened, but as said will post a follow up when I can deduce further information

**Additional information**
The game does seem to at least partly recognize that you're not supposed to be flying, since as soon as I touch the ground I can no longer use firework rockets.

**Comment by LemonHeadOnGit** [comment]
Update: I actually think this is caused by some sort of desync when flying fast. The mod seems to work fine initially, but when I start going very fast through chunks, then the effect of not exiting flight mode kicks in. The issue is that this desync doesn't seem to ever resolve once this happens, even when basically standing still while using the elytra.

**Comment by enjarai** [comment]
I'm quite sure this is a vanilla bug. Have you tried pressing sneak while in this state? Either way, its most likely not an issue with this mod.

**Comment by LemonHeadOnGit** [comment]
Hi, yes I have tried pressing sneak to no avail. I will double check with the normal elytra, but previous testing showed no issues.

**Comment by LemonHeadOnGit** [comment]
After retrying the test, yes this does seem to be the aforementioned vanilla bug. My apologies.
