### ISSUE TITLE
[Suggestion] More controller options / flight only controls

### ISSUE THREAD

**Issue by mineland-0066** [enjarai/do-a-barrel-roll#18]
Went right into flying and got so confused at first by the controls. Id usually control myself on a controller with a left stick and use the bumpers for the yaw, as well with an inverted camera on these situations.

Thing is, i dont like having the inverted camera all the time and id like to keep the vanilla controls and not have to flip the view and movement sticks manually, so an option to have the controls change to another layout either set by the user or with toggles when flight is activated would be really handy

**Comment by enjarai** [comment]
An option to invert the Y axis only during flight is already available, but much more than that isn't possible with MidnightControls, which I assume you're using for controller input. Their API is currently quite limited and doesn't allow me to change axis inputs without some very invasive mixins.

If they ever update their API, I'll try to support it, but for now this isn't feasible.
