### ISSUE TITLE
Switch Roll and Yaw setting makes both strafe keys and mouse X axis control yaw, and neither control roll

### ISSUE THREAD

**Issue by Zytronium** [enjarai/do-a-barrel-roll#180]
When I toggle on Switch Roll and Yaw, I cannot roll anymore because it appears to make both the strafe keys (A and D) and the mouse X axis control yaw instead of the strafe keys controlling roll. Or maybe the strafe keys control both roll and yaw (I have the roll sensitivity way down). I can see a bit of roll happening, but way more yaw. 

I am on Fabric 1.21.3

https://github.com/user-attachments/assets/97660271-8d80-4005-928b-26d4727138c6

**Comment by Zytronium** [comment]
I just figured out why this happens. It doesn't automatically swap the keybinds for roll left/right and yaw left/right when you toggle this option.

**Comment by enjarai** [comment]
This is working as intended. I don't want to modify player's settings arbitrarily when they change the config, so you'll have to do it manually.
