### ISSUE TITLE
Fabric API is not compatible with NeoForge

### ISSUE THREAD

**Issue by MinecraftFool** [enjarai/do-a-barrel-roll#182]
the error message is: File mods\fabric-api-0.110.0+1.21.1.jar is a Fabric mod and cannot be loaded
The reason I loaded the Fabric API is because when I originally downloaded the neoforge 1.21.1 edition of the mod, and added it to the mods folder, the game told me: Mod do_a_barrel_roll requires fabric_api any Currently, fabric_api is not installed.

**Comment by AkashiiKun** [comment]
For neoforge you need forgified fabric api.
https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

**Comment by MinecraftFool** [comment]
> For neoforge you need forgified fabric api. https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

Thank you so much.
