### ISSUE TITLE
Forge 1.19.2

### ISSUE THREAD

**Issue by Looodon** [enjarai/do-a-barrel-roll#24]
Forge: 43.1.33

Hey, 
Minecraft wouldn't launch when I added the "2.0.0 for Forge 1.19.2" version of the mod.

**Comment by enjarai** [comment]
Please add a crash report and logs.

**Comment by enjarai** [comment]
Hmm, it doesn't seem like anything is wrong here, tho I think it's probably an incompatibility with another mod. Could you try running without any other mods? If that works, you could try adding your other mods back in with a binary search to find the mod thats causing issues.

**Comment by enjarai** [comment]
Yea that version was broken, I'm publishing an update right now that should fix it.
