### ISSUE TITLE
[Crash] 1.18.2 Forge version crashes when using this mod

### ISSUE THREAD

**Issue by DarthCaesium** [enjarai/do-a-barrel-roll#26]
I'm not entirely sure what's causing the problem, but this is what happens when using the mod for me: https://paste.ee/p/PNkvN. Mods that I suspect might cause the crash are Rubidium (unlikely but possible), Starlight, Elytra Bounce (again unlikely but possible), Better Third Person and/or Elytra Physics.

**Comment by enjarai** [comment]
Fix will be pushed in the next update.

**Comment by enjarai** [comment]
Alright I did a dumb with 2.0.1 and the "fix" actually broke the entire mod. Reopening this as I rolled back those changes.

**Comment by enjarai** [comment]
Actual fix being published in 2.0.3, this time it shouldnt break anything.

**Comment by ZekerZhayard** [comment]
There is one thing that is very easy to overlook: the package name in the SPI (`META-INF/services/javax.annotation.processing.Processor`) will be also added to the module.
This mod only relocates the MixinExtras itself, but does not relocate the SPI.
