### ISSUE TITLE
1.19.2 Minecraft just doesnt start, not even a crash

### ISSUE THREAD

**Issue by Thisguyneedshelp** [enjarai/do-a-barrel-roll#27]
no idea why, heres the logs https://mclo.gs/YIOMXoX even tho they dont say much, there is no crash report it just wont start when this mod is installed.

**Comment by Thisguyneedshelp** [comment]
oh yeah forge is 43.1.43 minecraft 1.19.2

**Comment by enjarai** [comment]
I can't see anything wrong in the logs, could you try removing all other mods and adding them back in with a binary search? That should help narrow down if this is an incompatibility with something.

**Comment by Thisguyneedshelp** [comment]
binary search?

**Comment by enjarai** [comment]
Add half of the mods back in and test if it works. If it does, add half of the remaining mods back. If it doesn't, remove half of the mods you added. Rinse and repeat. It's a way to find conflicting mods quickly without having to add and remove every single one.

**Comment by Thisguyneedshelp** [comment]
ahh, yea i was doing something similar to that

**Comment by Thisguyneedshelp** [comment]
ill lyk when i identify which it is

**Comment by Thisguyneedshelp** [comment]
cataclysm seems to be incompatible for whatever reason, but there are still others

**Comment by Thisguyneedshelp** [comment]
hey its working on client side, but i just tested on server and im getting a crash with no report, heres the logs tho, sorry to bring more work https://mclo.gs/2W0FQ14
