### ISSUE TITLE
[Forge 1.18] Crash when entering elytra flight

### ISSUE THREAD

**Issue by FyreAlchemage** [enjarai/do-a-barrel-roll#29]
I suspect this is due to a performance mod or something of that nature, but unsure. [Here's my crash log](https://mclo.gs/kpCgtnP).

**Comment by enjarai** [comment]
Idk exactly whats causing this, but try updating Configured.

**Comment by enjarai** [comment]
It should™ be fixed in the upcoming 2.1.0 version.
