### ISSUE TITLE
Aggressive Left Turning

### ISSUE THREAD

**Issue by Daedalus706** [enjarai/do-a-barrel-roll#30]
When I'm flying with the while rolled to the left and I pull up or down the player rotates around Minecraft's Y-axis. This problem does not occur if I'm turning to the right. Also moving the mouse up or down results in a slight jump of the viewing angle

The problem occurs regardless of whether banking is on or off or inverted pitch is on or off.

I have included a short video of the effects of this problem [https://youtu.be/k0TBiQ_ieSE](url)
I didn't touch the a or d key in this clip.

I'm using game version 1.19.2 and mod version 2.2.0 (fabric)
The only other mods I have installed are optifabric, modmenu and shulkerbox tooltips

I hope this issue gets resolved quickly. Do a barrel roll is a really cool mod, but it's almost unplayable like this.

**Comment by enjarai** [comment]
Thats strange, I'm not sure what could be causing that. Could you try it without any other mods to eliminate factors? Especially optifabric, I've seen it causing some really weird and unexplainable issues before.

**Comment by enjarai** [comment]
Closing as wontfix for now due to optifabric being present, feel free to reopen if the issue persists after removing it.
