### ISSUE TITLE
[Forge1.18] Improper shading MixinExtras without relocating

### ISSUE THREAD

**Issue by LimonBlaze** [enjarai/do-a-barrel-roll#35]
### Problem
I've received an issue about incompatibility between Quicksand (Forge) and Do a Barrel Roll: https://github.com/ChannelingMC/quicksand-forge/issues/2

### Cause
After evaluating, the issue is caused by 2 modules exporting a same package, pointing to the fact that Do a Barrel Roll hasn't relocated its non-game library MixinExtras.

### Solution
Simply use `relocate` for the `shadowJar` task or move to Forge's Jar-in-Jar like what [Quicksand (Forge)](https://github.com/ChannelingMC/quicksand-forge) did should fix the issue.

**Comment by enjarai** [comment]
This has been fixed since 2.0.3, which is almost a month old. Please update to the latest version.
