### ISSUE TITLE
[WHAT?] Why is there a hack built in?

### ISSUE THREAD

**Issue by Camawama** [enjarai/do-a-barrel-roll#38]
You enabled a feature where players can change their speed with the Elytra in config. Anyone can just change their speed and cheat on my server. Is there a way to prevent this from being a thing?

**Comment by enjarai** [comment]
There is nothing builtin to circumvent vanilla or modded anti-cheat solutions, so I wouldn't consider it a hack. If this mod works for players on your server, there's nothing stopping them from using an actual hacked client, so this is something you should probably address.

I've attempted to make a way to disable the thrusting using a server packet, but this is difficult due to having to support both fabric and forge, and forge being stubborn when it comes to server-side.

**Comment by Camawama** [comment]
I love this mod and the boosting mechanic is cool, but I don't really see a need for it. I run a heavily modded server and I include your mod in the modpack. I don't know of a way to prevent players from abusing this. Even if I remove your mod, people can add it back and cheat. Any suggestions?

**Comment by enjarai** [comment]
I'd say just ban the use of the thrusting feature and punish anyone who uses it. Like I said, if people really wanted to cheat, they easily could in other ways, whether my mod exists or not. However, I do understand that I've made cheating more accessible with this feature.

I'll look into the feasibility of disabling thrusting from the server again, maybe taking a deeper dive into the pit of despair that is forge. Even if I did add this now though, or removed the feature entirely, users could still easily downgrade to an old version to bypass any efforts made, so you'll want to keep that in mind.

**Comment by Camawama** [comment]
Just make it so the client copies config from the server when they join. The server owner can then lock the thrust at what they want!!

**Comment by Kikugie** [comment]
That's the problem with forge, thats not as easy. In any case it's not like someone can't edit the mod themselves to ignore server config. If you see people cheating with or without the mod just ban them ¯⁠\⁠_⁠(⁠ツ⁠)⁠_⁠/⁠¯

**Comment by Camawama** [comment]
Someone needs to create a mod to limit the speed at which an Elytra can fly now.

**Comment by Camawama** [comment]
I am using https://chat.openai.com/chat to try and make a mod to limit the speed of the Elytra

**Comment by Kikugie** [comment]
Poor players tbh

**Comment by Azazelthedemonlord** [comment]
bruh openai

**Comment by enjarai** [comment]
bruh indeed, this can only end well.

**Comment by Camawama** [comment]
It was more or less a joke but I was curious as to if ChatGPT can make a working mod for that. It seems to have gotten it correct for the most part, except for the fact that it used old forge documentation instead of the current versions.

**Comment by Camawama** [comment]
https://www.curseforge.com/minecraft/mc-mods/nerfed-elytras

Someone already made it anyway.
