### ISSUE TITLE
[Enhancement] More realistic roll physics

### ISSUE THREAD

**Issue by enjarai** [enjarai/do-a-barrel-roll#4]
![image](https://user-images.githubusercontent.com/38552516/186241907-95bcadc0-e203-4e99-a2f3-332843807b58.png)

**Comment by XanderCreates** [comment]
wouldnt this increase the risk of being flagged by an anticheat

**Comment by XanderCreates** [comment]
Although, I would like this to be added. Because Since I flew in flight sims or something similar, i also took advantage of roll physics in manuevers. When I tried with this mod, it required me to use both pitch and roll to get a facsimile of roll physics, and even then it screwed with how i planned to fly

**Comment by floral-qua-floral** [comment]
> Wouldn't this increase the risk of being flagged by an anticheat?

Doubt it. If the player rotates 45 degrees clockwise and starts banking to the right, that's directly equivalent to a vanilla player just moving their mouse right. The server wouldn't be able to tell the difference between someone with this mod banking right by rolling, versus a vanilla player turning right by just moving the mouse.

**Comment by enjarai** [comment]
It really depends on the implementation. If it's limited to camera movement it should be fine.

**Comment by XanderCreates** [comment]
would it be possible to add sideslip if auto-yaw was countered while rolling? (basically your momentum would change and you would be moving sideways in the direction you rolled to)

**Comment by enjarai** [comment]
Implemented in 1.3.0.
