### ISSUE TITLE
Config Button Doesn't Show Up

### ISSUE THREAD

**Issue by LordEnder-Kitty** [enjarai/do-a-barrel-roll#45]
when i open the game with my mod set the do a barrel roll mod config button in the mod menu doesn't appear.
here are the logs from my game that i was asked to share on the curseforge comments

[latest.log](https://github.com/enjarai/do-a-barrel-roll/files/10322713/latest.log)

**Comment by enjarai** [comment]
Ah I see, it seems like YACL made an accidental breaking change in 2.1.1, which is what DABR uses. I'll try to include a proper error message for this, but it should just work™ if you update YACL to 2.1.1.
