### ISSUE TITLE
Version 2.5.1 prevents the server from stopping

### ISSUE THREAD

**Issue by BroOtti** [enjarai/do-a-barrel-roll#49]
Minecraft 1.19.3
Fabric Loader 0.14.12
Fabric API 0.72.0
do a barrel roll 2.5.1

If I try to stop the server, the cicada threads won't stop and keep the process alive.
The process needs to be killed. This behaviour prevents clean auto restarts.

See threaddump: https://hastebin.com/farapemifu.pl

**Comment by enjarai** [comment]
Oh I see, thats a big problem. It'd have been a while before I caught that one myself, so thanks for letting me know. I'll definitely look into it.

**Comment by enjarai** [comment]
Just published 2.5.2, it should contain a fix.
