### ISSUE TITLE
[Bug] Camera keeps momentum when pause screen is opened.

### ISSUE THREAD

**Issue by doinkythederp** [enjarai/do-a-barrel-roll#5]
Opening the pause screen while the camera still has momentum after moving the mouse doesn't cause the momentum to be lost, and the camera keeps turning while the game is paused.

**Comment by XanderCreates** [comment]
Should be fixed as of 1.1.0

**Comment by enjarai** [comment]
This wasn't actually fixed in 1.1.0, but I'll fix it in the next update.

**Comment by enjarai** [comment]
Fixed in 1.2.0
