### ISSUE TITLE
1.18.2 launches the game, crashes when entering the world/server

### ISSUE THREAD

**Issue by Widelczyna** [enjarai/do-a-barrel-roll#50]
Tried all update versions of this mod for 1.18.2 and for all it says the same thing when crushes:
The game crashed whilst unexpected error
Error: java.lang.IncompatibleClassChangeError: Class net.minecraftforge.common.ForgeConfigSpec$EnumValue does not implement the requested interface java.util.function.Supplier

And in crash reports it looks like that:
Description: Unexpected error

java.lang.IncompatibleClassChangeError: Class net.minecraftforge.common.ForgeConfigSpec$EnumValue does not implement the requested interface java.util.function.Supplier

I have some other mods, but as I look into the crash reports they're not really mentioned there.

**Comment by enjarai** [comment]
Do you have Configured installed?

**Comment by Widelczyna** [comment]
I installed it now, but it didn't change anything - the issue remains the same

**Comment by enjarai** [comment]
Try updating your forge version?

**Comment by Widelczyna** [comment]
Okay it was 40.1.0 and I changed to 40.2.0 and it started to work! Thank you!

Awesome mod btw

**Comment by enjarai** [comment]
👍
