### ISSUE TITLE
Do A Barrel Roll has failed to load correctly

### ISSUE THREAD

**Issue by Ch1216** [enjarai/do-a-barrel-roll#53]
Happens in the latest update, Forge 40.2.0, 1.18.2
java.lang.InvocationTargetException: null
[crash-2023-01-30_17.36.57-fml.txt](https://github.com/enjarai/do-a-barrel-roll/files/10540597/crash-2023-01-30_17.36.57-fml.txt)
[latest.log](https://github.com/enjarai/do-a-barrel-roll/files/10540598/latest.log)

**Comment by enjarai** [comment]
Turns out I pushed a broken forge version by accident. It should be fully working in 2.6.1, which I just released, but feel free to make a new issue if there are more problems I didn't catch.
