### ISSUE TITLE
Version 2.6.1 for 1.18.2 Forge does not work.

### ISSUE THREAD

**Issue by nthxny** [enjarai/do-a-barrel-roll#55]
Mod does nothing, Elytra behavior is unchanged, though it loads and still has keybinds. The previous release, 2.5.3, works fine.

**Comment by enjarai** [comment]
Please share your logs, config file and modlist.

**Comment by nthxny** [comment]
Just vanilla with only this mod, the latest version isn't working. No mention of anything in the logs.

**Comment by enjarai** [comment]
If you delete/move the config file for the mod, does it regenerate when starting the game? It should be in `.minecraft/config/`.

**Comment by Ch1216** [comment]
Happens to me too
[latest.log](https://github.com/enjarai/do-a-barrel-roll/files/10564678/latest.log)
[do_a_barrel_roll-client.txt](https://github.com/enjarai/do-a-barrel-roll/files/10564685/do_a_barrel_roll-client.txt)

**Comment by enjarai** [comment]
Hmmm, I can't replicate this on my computer. Does it happen with the 1.19.2 or 1.19.3 version as well?

**Comment by enjarai** [comment]
I'm looking into this issue, for now you can downgrade to 2.5.x as a workaround.

**Comment by Ch1216** [comment]
How come you pushed a version to fix the issue on every version except forge 1.18.2

**Comment by enjarai** [comment]
> How come you pushed a version to fix the issue on every version except forge 1.18.2

2.6.2 was an attempted fix which didn't end up working. Since I currently have no idea what the problem is, I've removed the 2.6.x versions for forge 1.18.2 as a workaround for now. This'll at least ensure people don't download a broken version when grabbing the latest available.

**Comment by enjarai** [comment]
I've recently dropped support for 1.18.2, so this will not be looked into any further.
