### ISSUE TITLE
[FORGE] [1.18.2] MR.CRAYFISH GUN MOD INCOMPATABILITY

### ISSUE THREAD

**Issue by Camawama** [enjarai/do-a-barrel-roll#58]
**Describe the issue**
Mr. CrayFish's gun mod adds a swaying animation that appears to completely mess up the camera for your mod.

**Comment by Camawama** [comment]
I don't know enough about the camera roll stuff to make these two compatible but here is my issue report for their mod (I'm really only sending this here so it pops up on the other issue page) : https://github.com/MrCrayfish/MrCrayfishGunMod/issues/431

**Comment by enjarai** [comment]
Can you add a video showing the broken movement?

**Comment by Camawama** [comment]
https://user-images.githubusercontent.com/43620900/221059361-a07a2358-e050-49f3-9d79-9f8fb561c96c.mp4


You might not be able to tell but the camera is moving quickly in direction when I'm trying to smoothly turn

**Comment by Camawama** [comment]
It's hard to tell unless you play and try it yourself.

**Comment by enjarai** [comment]
Do you have optifine installed?

**Comment by Camawama** [comment]
![image](https://user-images.githubusercontent.com/43620900/221458165-9b0482ed-4464-43ca-aaee-c70db80c6009.png)

![image](https://user-images.githubusercontent.com/43620900/221458223-2e3202f7-7236-4287-a0a9-f293ba399ec3.png)

![image](https://user-images.githubusercontent.com/43620900/221458384-40215598-9859-4569-95f5-559fe3e72cc0.png)

![image](https://user-images.githubusercontent.com/43620900/221458444-dbb2b5d9-89b7-4866-b698-779ecdfef578.png)

![image](https://user-images.githubusercontent.com/43620900/221458473-b5a74094-2728-4abf-b687-712527ef8da1.png)
![image](https://user-images.githubusercontent.com/43620900/221458565-5a09b1fa-bdd1-4e7d-a9b2-5b1302b7e335.png)


![image](https://user-images.githubusercontent.com/43620900/221458601-09aed771-9cbf-4fdd-a937-2c2d7b98b6fd.png)

![image](https://user-images.githubusercontent.com/43620900/221458668-b10b4462-cd8e-41a4-8d3f-cf2ddb7a3880.png)

![image](https://user-images.githubusercontent.com/43620900/221458739-4b92be76-65bd-443a-bbbf-26a7912da3ff.png)

![image](https://user-images.githubusercontent.com/43620900/221458784-7a2a7055-ed7d-4b39-900d-7026e5c1d32b.png)

![image](https://user-images.githubusercontent.com/43620900/221459001-bd2d4f97-bc9a-46c8-9761-15070b43eff2.png)

![image](https://user-images.githubusercontent.com/43620900/221459041-ff560d9c-d003-4a88-8f99-3f875ab9ebec.png)

**Comment by Camawama** [comment]
hello

**Comment by Camawama** [comment]
Do you think any of those performance mods are the culprit?

**Comment by enjarai** [comment]
I don't see how, but I also don't see any code in the gun mod that could conflict. Forge is not a primary supported platform due to my limited knowledge of it, so you're probably better off looking for a fix on gun mod's side.
