### ISSUE TITLE
1.18 p l e a s e !!

### ISSUE THREAD

**Issue by dlfnn** [enjarai/do-a-barrel-roll#6]
This mod is my dream mod, but the _Great Border of Versions_ stops me from my dream. Please, it would be so nice if there is a 1.18.x version of it! 
I know I shouldn't ask much if you didn't since this is for free, but, please. 
Even if you decide not to, I would still thank you so much for the mod <3

**Comment by enjarai** [comment]
I suppose there are still a bunch of people playing 1.18... 

I can't promise I'll maintain it, but the next update will come with a 1.18.2 version.

**Comment by enjarai** [comment]
1.2.0+1.18 published.

**Comment by dlfnn** [comment]
Thanks so much
