### ISSUE TITLE
Enhancement: Add a config option that Inverts Up and down controls when flying

### ISSUE THREAD

**Issue by Mr-Aerod** [enjarai/do-a-barrel-roll#62]
**Describe the enhancement**
My proposal is to add an optional config feature that makes it so the up and down controls are inverted when flying with elytra - this applies for when you move the mouse up, the player goes down instead of up and vice versa.

As someone who is currently in the process of learning to fly a glider, I find this much more realistic and convenient to use.

**Comment by enjarai** [comment]
This is already an option, check out the "invert pitch" toggle in the config.
