### ISSUE TITLE
No Elytra cape texture with the mod installed

### ISSUE THREAD

**Issue by BlizzLee** [enjarai/do-a-barrel-roll#65]
**Describe the issue**
So with the Barrel Roll mod installed, I can't see my Vanilla cape texture on my Elytra. Nor can I see my custom cape Elytra texture I use from the Capes mod. I only see the default Elytra texture.

**Crash report/logs (if applicable)**
Here's a Spark log which contains all of my installed mods and extra details - https://spark.lucko.me/oyTGQHNMhv
I only really have the latest version of the Fabulously Optimized modpack installed with a few extra mods I added.

**Additional information**A
At first I thought that the Wavey Capes and Capes mods might be the reason for this issue, but I uninstalled both of these mods and I still don't see a Elytra cape texture with Barrel Roll installed.

**Comment by BlizzLee** [comment]
Awesome! :D I will be sure to test it out

**Comment by enjarai** [comment]
Actually, could you try out this actions build before I publish it? It should hopefully fix the issue.
https://github.com/enjarai/do-a-barrel-roll/actions/runs/4699116065

**Comment by BlizzLee** [comment]
Sure, 1 moment

**Comment by BlizzLee** [comment]
It works! :D 
![image](https://user-images.githubusercontent.com/130601516/232030418-ea261916-c13c-46f1-8cac-e2b9629fcaa8.png)

**Comment by enjarai** [comment]
Epic, I'll publish this as a new version then.
