### ISSUE TITLE
"Use momentum based camera" breaks rendering, causes freezes, and softlocks world saves by setting player rotation to NaN

### ISSUE THREAD

**Issue by PolarBear-svg** [enjarai/do-a-barrel-roll#73]
**Describe the issue:**
The "Use momentum based camera" option occasionally works if "show momentum widget" is disabled but mouse or keyboard input does nothing. Otherwise it simply prevents the game from rendering (see attached image).
The other half of the time it freezes the minecraft instance which when closed softlocks the player from joining the server by setting rotating to NaN. This would mean enabling it on an online server would require an admin to reset/rollback player data to allow connection to the server again.

**Crash report/logs:**
Similar logs occurred when using sodium

- Trying to join a soft locked world: [https://mclo.gs/Ux33m9r](https://mclo.gs/Ux33m9r)
- Result of resetting the config from a previously soft locked state and then enabling the feature again on a different world: [https://mclo.gs/l3YBvWV](https://mclo.gs/l3YBvWV)

**Additional information:**
Game view when attempting to use the Elytra:
![Screenshot_2023-05-15-01-16-33_1920x1080](https://github.com/enjarai/do-a-barrel-roll/assets/72043633/8964d3f3-d4bc-4f9d-ad7f-b94e2b5e2418)

I would recommend disabling this feature to prevent players from soft locking their games accidentally until a solution can be found. I really like this mod thanks for putting so much work into it!

**Comment by enjarai** [comment]
Ah thats bad, thanks for letting me know. I'll look into it and push out an update asap.

**Comment by enjarai** [comment]
Just published 2.7.4 with a fix for this issue, momentum based mouse should now work as expected again.
