### ISSUE TITLE
can't open config menu  with mod menu

### ISSUE THREAD

**Issue by LiamTheNinja5** [enjarai/do-a-barrel-roll#78]
**system**
OS: SteamOS (arch linux)
Game version: 1.19.4
Fabric version: 0.14.21

**recreate**
install fabric
install mod menu (ver 6.22)
install do a barrel roll (ver 2.8.3+1.19.4)
launch minecraft
click "mods" button
hover over do a barrel roll

**Crash report/logs**
![image](https://github.com/enjarai/do-a-barrel-roll/assets/50884811/b414a0b5-68c0-459d-a7ac-56d05783d05c)

**Comment by MenacingPerson** [comment]
Download the mod "Yet Another Config Lib"

https://modrinth.com/mod/yacl

**Comment by enjarai** [comment]
More specifically, do not use the 3.0.0 betas of YACL. Use this version instead: https://modrinth.com/mod/yacl/version/2.5.1+1.19.4-fabric

**Comment by LiamTheNinja5** [comment]
@MenacingPerson I already have it
![image](https://github.com/enjarai/do-a-barrel-roll/assets/50884811/8bfa2dfa-05d8-47ae-ae8e-bd1cb4d1d6e6)

**Comment by LiamTheNinja5** [comment]
> More specifically, do not use the 3.0.0 betas of YACL. Use this version instead: https://modrinth.com/mod/yacl/version/2.5.1+1.19.4-fabric

ahh, downgrading now

**Comment by LiamTheNinja5** [comment]
Thankyou

**Comment by enjarai** [comment]
When 1.20 releases, I'll update DABR to use the new YACL API. For now, you'll have to stick with an older version though.

**Comment by Estecka** [comment]
> More specifically, do not use the 3.0.0 betas of YACL. Use this version instead: https://modrinth.com/mod/yacl/version/2.5.1+1.19.4-fabric

Hi, I ended up here because the [dependency list](https://modrinth.com/mod/do-a-barrel-roll/version/2.8.3+1.19.4-fabric) on Modrinth do list YACL 3.0.0 as a requirement. You might want to update the page so it lists 2.5.1 instead.

**Comment by enjarai** [comment]
Ah, guess it automatically picked up the latest version. I'll update it.
