### ISSUE TITLE
[1.20] Held keys are kept down between activation/deactivation of DABR

### ISSUE THREAD

**Issue by Estecka** [enjarai/do-a-barrel-roll#80]
**Describe the issue**

If keys are being held while landing, taking off, or while enabling/disabling DABR in flight, then this key will be artificially held down the next time I land/take-off/etc.
This seems to apply only to keys that have been bound to both DABR action and vanilla action in the keybinding menu.

For example: 
I have a key assigned to both "Strafe Left" and "Roll Left"
- If I take off while strafing left, the next time I land, my character will continuously strafe left, until I press the key again.
- If I land while rolling to the left, then the next time I take off, my character will immediately and continuously roll left, until I press the key again.

**Crash report/logs (if applicable)**
Nothing in the log appears to stand out: 
https://mclo.gs/S4XYC1U

**Additional information**
Mod list (from the log):
- do_a_barrel_roll 3.0.0-beta.1+1.20
- fabric-api 0.83.0+1.20
- fabricloader 0.14.21
- minecraft 1.20
- modmenu 7.0.1
- sodium 0.4.10+build.27
- yet_another_config_lib_v3 3.0.1+1.20

**Comment by enjarai** [comment]
Ah yea I think I know whats going on here, I'll see if I can fix it later today.

**Comment by enjarai** [comment]
Fixed in beta.2
