### ISSUE TITLE
[1.20] Horizon widget causes several things to render incorrectly

### ISSUE THREAD

**Issue by Estecka** [enjarai/do-a-barrel-roll#81]
**Describe the issue**
While flying with the horizon widgets enabled, several things will render incorrectly:  
- The sky, especially at certain times of the day, will show odd colours in one of its half.
- The background of the Mod Menu will appear transparent.
- The icons of status effect in the corner of the screen will appear semi-transparent.

The momentum widget does not cause this issue.
Having the F3 menu open will prevent the issue from appearing
A message being shown in the chat log will prevent the issue from appearing. (Taking a screenshot logs a message to the chat, but the incorrect colors still appear on the screenshot.)

**Crash report/logs (if applicable)**
Nothing outstanding happening in the logs: https://mclo.gs/qnpSMB2

**Additional information**
Screenshots: https://imgur.com/a/ajT5Qtl
To reproduce this exact sky, you may set `doDailightCycle` to false, and set time to `night`

Mod list:
- do_a_barrel_roll 3.0.0-beta.1+1.20
- fabric-api 0.83.0+1.20
- fabricloader 0.14.21
- minecraft 1.20
- modmenu 7.0.1
- yet_another_config_lib_v3 3.0.1+1.20

**Comment by enjarai** [comment]
:concern:

I'm sure glad I made this new version a beta first.

**Comment by enjarai** [comment]
Fixed in beta.2
