### ISSUE TITLE
thrusting not working

### ISSUE THREAD

**Issue by ilobilo** [enjarai/do-a-barrel-roll#82]
**Describe the issue**
Thrusting does not work on singleplayer.
``allowThrusting`` is set to true in ``*_server.json`` located in singleplayer mc instance config folder. thrusting is also enabled, with hotkey set to w but when I try to use it, nothing happens

**Additional information**
mc version: 1.20
dabr version: beta 2

worked fine on 1.19.4

**Comment by enjarai** [comment]
I'm not able to replicate this issue with the information you provide. Do you have the "Thrust Forward" keybind set, or did you accidentally bind W to "Toggle Thrusting"?

![image](https://github.com/enjarai/do-a-barrel-roll/assets/38552516/6a858e20-887e-4abe-b016-32eaff80ad2f)

I can't think of anything else that might cause this issue.

**Comment by ilobilo** [comment]
yes that was the issue thanks
also can I use thrusting with regular elytra flight?

**Comment by enjarai** [comment]
No, it only works when the mod is enabled.
