### ISSUE TITLE
Game Crashes when trying to launch Minecraft

### ISSUE THREAD

**Issue by Dormant11** [enjarai/do-a-barrel-roll#84]
When opening the game from the launcher in 1.19.4 the game crashes.

Error Message:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'do_a_barrel_roll'!

The mod worked yesterday but now it does not work for some reason.

**Comment by enjarai** [comment]
This is most likely #75, try installing YACL.

**Comment by Unthink4ble** [comment]
Nope, still crashes


> This is most likely #75, try installing YACL.

**Comment by enjarai** [comment]
Please share a full log file and crash report then.

**Comment by Unthink4ble** [comment]
Seems like its my Problem, bc if I just use the mod with yacl alone it works, I will tell you wich mods arent supported later

**Comment by Unthink4ble** [comment]
It doesnt support Optifine :/

**Comment by enjarai** [comment]
Yes, none of my mods support optifine. It's way too invasive to be compatible. Consider switching to modern (and better in every way) alternatives.
