### ISSUE TITLE
nevermind

### ISSUE THREAD

**Issue by inikishev** [enjarai/do-a-barrel-roll#87]
baobab nuts from wilder wild are incompatible with twigs

**Comment by enjarai** [comment]
The log spam shouldn't cause any issues, it's normal for debug.log to contain things like that. 

I don't see any indication that this mod is the source of the issue, could you make a minimal reproduction example? E.g. the smallest set of mods that has the issue?

Maybe also check if removing DABR fixes it.

**Comment by inikishev** [comment]
ok so it still does that without do a barrel roll but it took like 5 hours this time. so idk
