### ISSUE TITLE
Game crashes when loading into a world

### ISSUE THREAD

**Issue by JordanGuyOne** [enjarai/do-a-barrel-roll#88]
**Describe the issue**
launcher and Minecraft will load perfectly fine but will suddenly crash just before loading into a world and yes i tried installing YACL and Cloth Config API

**Crash report/logs (if applicable)**
the crash snippet is as follows:

The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class net.minecraft.client.player.LocalPlayer tried to access private field net.minecraft.world.entity.Entity.f_19861_ (net.minecraft.client.player.LocalPlayer and net.minecraft.world.entity.Entity are in module minecraft@1.20.1 of loader 'TRANSFORMER' @79add732)

heres the full crash log:

https://mclo.gs/LMUCCfe

**Additional information**
I am using forge 1.20.1, the mod is only rated for 1.19.4 but it should still work as most other mods do. there is an updated version for fabric but am reluctant to change over as it would mean reinstalling all of my current mods and having to learn a new system. is there any chance that this mod will be updated to 1.20.1 on the forge version or am I out of luck?

**Comment by enjarai** [comment]
The Forge version of this mod will not work with 1.20+ and wont be receiving any more updates. It was a massive pain to maintain two versions at once, and Forge was limiting what I could do with the mod, so I've stopped supporting it as of 1.20.

Fabric is very similar to Forge from a user perspective (if not from a mod author one), so I'd recommend switching if you're able.
