### ISSUE TITLE
DABR Movement keybinds override vanilla movement

### ISSUE THREAD

**Issue by AlfmanOO7** [enjarai/do-a-barrel-roll#89]
**Describe the issue**
When the DABR movements are bound to either the A or W keys, even when not in flight.

Here are my logs: (although I don't think they'll help)

https://mclo.gs/oANXMzl

I have reset the configs for the mod, 

This config is stable: (but I cannot use the DABR mod as I would like)
![image](https://github.com/enjarai/do-a-barrel-roll/assets/62825044/5f2135c1-9543-49c5-9558-22ffbbce78f1)
This prevents me from using the W or A keys to move:
![image](https://github.com/enjarai/do-a-barrel-roll/assets/62825044/e47819b6-5955-466d-8a40-385d4c1148e2)

**Comment by enjarai** [comment]
This is most likely to be a mod conflict of some kind. Are you using any other mods that do unusual stuff with keybindings? Can you reproduce the issue when only DABR is installed?

**Comment by enjarai** [comment]
This is a compatibility issue with Equipment Compare and not something I can fix on my side, see https://github.com/AHilyard/EquipmentCompare/issues/31.

**Comment by enjarai** [comment]
I've implemented a workaround on my side that may break some functionality of Equipment Compare. In my testing it was fine, but I'm not sure it's without side effects.

A proper fix will still have to come from EC's author.
