### ISSUE TITLE
1.19.2 doesn't work

### ISSUE THREAD

**Issue by Saiko125** [enjarai/do-a-barrel-roll#9]
just downloaded the latest version for 1.19.2 and mod says it's not compatible with this version and it crashed with fabric error saying 

![obraz_2022-08-25_201154957](https://user-images.githubusercontent.com/86660217/186738612-8db78916-6dba-46dc-bbbb-749c50e11112.png)

what could be the cause ?

**Comment by enjarai** [comment]
Yea I made a mistake with the version requirement, its fixed in 1.2.1.
