### ISSUE TITLE
1.20.1 fabric. Crash when I try to ponder something in create mod.

### ISSUE THREAD

**Issue by carson-coder** [enjarai/do-a-barrel-roll#91]
**Describe the issue**
Whenever I try to ponder something in create mod with this mod my game crashes. Looking at the logs it looks like it crashes when create mod is moving the camera.

**Crash report/logs (if applicable)**
Full logs: https://mclo.gs/7B3hBTk
Important Part: https://mclo.gs/QYBtuiE

**Additional information**
I am using the beta version of fabric create. (https://github.com/Fabricators-of-Create/Create/actions/runs/5775420762)

Edit: I think it has something to do with https://github.com/enjarai/do-a-barrel-roll/blob/1.20/dev/src/main/java/nl/enjarai/doabarrelroll/mixin/roll/CameraMixin.java#L123

**Comment by enjarai** [comment]
> Edit: I think it has something to do with [`1.20`/dev/src/main/java/nl/enjarai/doabarrelroll/mixin/roll/CameraMixin.java#L123](https://github.com/enjarai/do-a-barrel-roll/blob/1.20/dev/src/main/java/nl/enjarai/doabarrelroll/mixin/roll/CameraMixin.java?rgh-link-date=2023-08-06T20%3A26%3A55Z#L123)

Seems like it yes, I suppose Create calls camera functions in an unorthodox order. Should be an easy fix luckily, give me a bit.

**Comment by enjarai** [comment]
Fixed in 3.0.2.
