### ISSUE TITLE
Add option to disable kinetic damage, optionally only at lower speeds

### ISSUE THREAD

**Issue by EvelynTSMG** [enjarai/do-a-barrel-roll#92]
This would allow the player to not fall prey to the elytra's janky functionality regarding damage taken upon "landing".
In some cases, this may lead to players taking a lot of damage (especially when not wearing armor) while attempting to land at reasonably low speeds.
This should probably be off by default, and maybe a dropdown? Something like

Disable Kinetic Damage
|= Never
|- At low speeds
|- Always

**Comment by enjarai** [comment]
Great idea, I'll see if I can add it for the next update. It might take a bit though, since I'm working on some major code reshuffles.

**Comment by craftish37** [comment]
Love the idea, here's some matter to work with !
https://www.youtube.com/watch?v=fbfVGIBcD8c
https://en.wikipedia.org/wiki/Terrain_awareness_and_warning_system
https://en.wikipedia.org/wiki/Ground_proximity_warning_system

**Comment by enjarai** [comment]
Added in 3.1.0.
