### ISSUE TITLE
do-a-barrel-roll crashing Quilt

### ISSUE THREAD

**Issue by 3quarterscolon** [enjarai/do-a-barrel-roll#95]
**Describe the issue**
do-a-barrel-roll 3.1.0 started causing an unspecified fatal internal error in Quilt 19.2 after I updated some mods. I can't remember whether it was one of them.

**Crash report/logs (if applicable)**
https://mclo.gs/gDWgooh

**Additional information**
None.

**Comment by enjarai** [comment]
Fixed in 3.1.1.
