### ISSUE TITLE
Mod not working.

### ISSUE THREAD

**Issue by Pullolo** [enjarai/do-a-barrel-roll#97]
When I added the Explorer's Compass the mod stopped working in a sense that altough the mod was enabled elytra acted like the vanilla one.

There is no crash and there aren't any errors in the logs.

**Comment by enjarai** [comment]
Can't reproduce, there might be some other conflict. Can you send a log anyway?

![image](https://github.com/enjarai/do-a-barrel-roll/assets/38552516/e1b4503c-93af-45fa-b204-706ede178a74)

**Comment by Pullolo** [comment]
Oh wait sorry, I meant Naturte's Compass, My bad I got those two mixed up with eachother, I can't send the log right now so I will attach it later.

**Comment by Pullolo** [comment]
[latest.log](https://github.com/enjarai/do-a-barrel-roll/files/12324928/latest.log)

**Comment by Pullolo** [comment]
After restarting my PC yeasterday the problem still occured, after restarting it now it fully works, I have no Idea what's going on but thank you for help anyway, it just started working out of nowhere.
